apps/jobs/urls.py
from django.urls import path

from . import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobListView.as_view(), name="jobs-home"),
    path("jobs/new/", views.JobCreateView.as_view(), name="job-create"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job-detail"),
    path(
        "companies/<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        include("jobs.urls", namespace="jobs"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/jobs/models.py
from django.db import models

from cloudinary.models import CloudinaryField as BaseCloudinaryField
from core.models import BaseModel
from tinymce.models import HTMLField
import jobs.choices as choices


class CloudinaryField(BaseCloudinaryField):
    def upload_options(self, model_instance):
        return {
            'public_id': model_instance.name,
            'unique_filename': False,
            'overwrite': True,
            'resource_type': 'image',
            'invalidate': True,
            'quality': 'auto:eco',
        }


class JobPost(BaseModel):
    """ Job Post """

    title = models.CharField(max_length=200)
    description = HTMLField()
    job_type = models.CharField(choices=choices.JOB_TYPE_CHOICES, max_length=100)
    job_location = models.CharField(max_length=200)
    job_category = models.CharField(
        choices=choices.JOB_CATEGORY_CHOICES, max_length=100
    )
    regional_restrictions = models.CharField(
        choices=choices.REGIONAL_RESTRICTIONS_CHOICES, max_length=100
    )
    application_url = models.CharField(max_length=200)
    company = models.ForeignKey(
        "Company", on_delete=models.CASCADE, related_name="job_posts"
    )

    class Meta:
        ordering = ["-created_on"]
        verbose_name = "Job Post"
        verbose_name_plural = "Job Posts"

    def __str__(self):
        return self.title


class Company(BaseModel):
    """ Company posting the job """

    name = models.CharField(max_length=200)
    company_statement = models.CharField(max_length=500)
    headquarters = models.CharField(max_length=200)
    logo = CloudinaryField(blank=True, null=True)
    url = models.CharField(max_length=200)
    email = models.CharField(max_length=200, blank=True, null=True)
    description = HTMLField()

    class Meta:
        ordering = ["-created_on"]
        verbose_name_plural = "Companies"

    @property
    def num_jobs_posted(self):
        return self.job_posts.count()

    def __str__(self):
        return self.name

apps/jobs/forms.py
from django import forms

from tinymce.widgets import TinyMCE

import jobs.choices as choices
from .models import Company, JobPost


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class JobPostForm(forms.Form):
    job_title = forms.CharField()
    job_application_url = forms.CharField()
    job_description = forms.CharField(widget=TinyMCEWidget())
    job_type = forms.ChoiceField(
        choices=choices.JOB_TYPE_CHOICES, widget=forms.RadioSelect
    )
    job_location = forms.CharField()
    job_category = forms.ChoiceField(choices=choices.JOB_CATEGORY_CHOICES)
    job_regional_restrictions = forms.ChoiceField(
        choices=choices.REGIONAL_RESTRICTIONS_CHOICES
    )
    company_name = forms.CharField()
    company_statement = forms.CharField()
    company_logo = forms.ImageField()
    company_url = forms.URLField()
    company_email = forms.EmailField()
    company_description = forms.CharField(widget=TinyMCE())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial["job_category"] = "programming"
        self.initial["job_type"] = "full_time"
        self.initial["job_regional_restrictions"] = "anywhere"

apps/jobs/views.py
from collections import defaultdict

from django.db.models import Count
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import DetailView, ListView, FormView

from .choices import (
    JOB_TYPE_CHOICES,
    JOB_CATEGORY_CHOICES,
    REGIONAL_RESTRICTIONS_CHOICES,
)
from .models import JobPost, Company
from .forms import JobPostForm


class JobListView(ListView):
    model = JobPost
    template_name = "jobs/job_list.html"
    context_object_name = "job_posts"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        header_name = ""

        if "job_type" in self.request.GET:
            try:
                job_type = JOB_TYPE_CHOICES[self.request.GET.get("job_type")]
                header_name = job_type
            except KeyError:
                pass

        if "job_category" in self.request.GET:
            try:
                job_category = JOB_CATEGORY_CHOICES[
                    self.request.GET.get("job_category")
                ]
                header_name = job_category
            except KeyError:
                pass

        if "regional_restrictions" in self.request.GET:
            try:
                regional_restrictions = REGIONAL_RESTRICTIONS_CHOICES[
                    self.request.GET.get("regional_restrictions")
                ]
                header_name = regional_restrictions
            except KeyError:
                pass

        context["header_name"] = header_name
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        job_type = self.request.GET.get("job_type", None)
        if job_type:
            queryset = queryset.filter(job_type=job_type)

        job_category = self.request.GET.get("job_category", None)
        if job_category:
            queryset = queryset.filter(job_category=job_category)

        regional_restrictions = self.request.GET.get("regional_restrictions", None)
        if regional_restrictions:
            queryset = queryset.filter(regional_restrictions=regional_restrictions)

        grouped_job_posts = defaultdict(list)
        for job_post in queryset.iterator():
            grouped_job_posts[job_post.get_job_category_display()].append(
                {
                    "id": job_post.id,
                    "title": job_post.title,
                    "company": job_post.company,
                    "get_job_type_display": job_post.get_job_type_display(),
                    "job_location": job_post.job_location,
                    "created_on": job_post.created_on,
                }
            )
        return dict(grouped_job_posts)


class JobCreateView(FormView):
    form_class = JobPostForm
    template_name = "jobs/job_create.html"

    def get_success_url(self):
        return reverse("jobs:jobs-home")

    def form_valid(self, form):
        company = Company()
        company.company_statement = form.cleaned_data.get("company_statement")
        company.description = form.cleaned_data.get("company_description")
        company.email = form.cleaned_data.get("company_email")
        company.logo = form.cleaned_data.get("company_logo")
        company.name = form.cleaned_data.get("company_name")
        company.url = form.cleaned_data.get("company_url")
        company.save()

        job_post = JobPost()
        job_post.company = company
        job_post.application_url = form.cleaned_data.get("job_application_url")
        job_post.description = form.cleaned_data.get("job_description")
        job_post.job_category = form.cleaned_data.get("job_category")
        job_post.job_location = form.cleaned_data.get("job_location")
        job_post.job_type = form.cleaned_data.get("job_type")
        job_post.regional_restrictions = form.cleaned_data.get(
            "job_regional_restrictions"
        )
        job_post.title = form.cleaned_data.get("job_title")
        job_post.save()
        return redirect(self.get_success_url())


class JobDetailView(DetailView):
    model = JobPost
    template_name = "jobs/job_detail.html"
    context_object_name = "job_post"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        job_post = self.get_object()
        related_jobs = JobPost.objects.filter(
            job_category=job_post.job_category
        ).exclude(id=job_post.id)[:3]
        context["posts"] = related_jobs
        return context


class CompanyDetailView(DetailView):
    model = Company
    template_name = "jobs/company_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        company = self.get_object()
        related_jobs = JobPost.objects.filter(company=company)
        context["posts"] = related_jobs
        return context

apps/jobs/templates/jobs/company_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% load widget_tweaks %}
<main role="main">
    <div class="job-nav">
        <a href="/">
            <p><span id="arrow-left">←</span> Back to all jobs </p>
        </a>
    </div>
    <div class="content">
        <div class="company-detail">
            <div class="listing-header">
                <div class="listing-header-container">
                    <div class="listing-logo" style="background-image: url({{company.logo.url}});">
                    </div>
                    <h1> {{company.name}} </h1><br>
                    <h3>
                        <i class="fas fa-map-marker-alt" style="margin-left: 0px;"></i>
                        {% if company.headquarters %}
                        {{company.headquarters}}
                        {% else %}
                        Remote
                        {% endif %}
                    </h3><br>
                    <h4> Jobs posted: {{company.num_jobs_posted}} </h4><br>
                    <div class="listing-tools">
                        <div class="tools">
                        </div><a target="_blank" href="{{company.url}}">
                            <h5> View website <span id="arrow-right">→</span></h5>
                        </a>
                    </div>
                </div>
            </div>
            <section class="company">
                <div class="company-description">
                    {{company.description|safe}}
                </div>
            </section>

        </div>
        <div class="jobs-container">
            <section class="jobs company-jobs">
                <article>
                    <h2> All {{company.name|capfirst}} Jobs
                        <span class="font-weight-light h6 latest_post">
                            Latest post about {{posts.0.created_on|timesince}} ago
                        </span>
                    </h2>
                    {% include "jobs/job_posts.html" %}
                </article>
            </section>
        </div>
    </div>
</main>
{% endblock content %}

apps/jobs/templates/jobs/job_create.html
{% extends "base.html" %}

{% block content %}
{% load widget_tweaks %}
<main role="main" class="job-new">
    <div class="container">
        <section class="row">
            <div class="job-nav">
                <a href="/">
                    <p style="float: left;z-index: 999;"><span id="arrow-left">←</span> Back to all jobs </p>
                </a>
            </div>
        </section>
        <section class="row">
            <div class="col">
                <form class="job-form mx-auto" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            {% if form.errors %}
                            <div class="error-block text-danger">* Please fix the errors below</div>
                            {% endif %}
                            <h4 class="text-danger">Tell Us About The Position
                                <span class="required-field-label">REQUIRED
                                    FIELDS <p class="required-field">●</p></span>
                            </h4>
                        </div>

                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Job Title</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_title class+="form-control form-control-lg" %}
                            <span class="input-text">Example: “Senior Designer”. &nbsp; Titles must describe one
                                position.</span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Category</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_category class+="form-control form-control-lg" %}
                        </div>
                        <div class="form-group col-md-6 job-type">
                            <label>Job Type</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_type %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label>Job Location</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_location class+="form-control form-control-lg" %}
                            <span class="input-text">Example: “Chicago, IL”, “Stockholm, Sweden”</span>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="inputCity">Regional Restrictions</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_regional_restrictions class+="form-control form-control-lg" %}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="inputState">How To Apply</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_application_url class+="form-control form-control-lg" %}

                            <span class="input-text">Link to Application page or Email address</span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group {% if form.job_description.errors %} has-error{% endif %}col-md-12">
                            <label for="inputZip">Job Description</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.job_description rows="10" cols="30" title="Hello, world!" %}
                            <div class="error-block text-danger">{{ form.job_description.errors }}</div>
                        </div>
                    </div>
                    <br>
                    <br>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <h4 class="text-danger">Tell Us More About Your Company</h4>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Company Name</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_name class+="form-control form-control-lg" %}
                            <span class="input-text">Enter your company or organization’s name.</span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label>Company Statement</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_statement class+="form-control form-control-lg" %}
                            <span class="input-text">Enter your company or organization’s mission statement. This will
                                be displayed on your company’s profile</span>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group {% if form.company_logo.errors %} has-error{% endif %}col-md-12">
                            <label>Logo</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_logo class+="form-control form-control-lg" %}
                            <span class="input-text">It’s highly recommended to use your Twitter or Facebook avatar.
                                Optional — Your company logo will appear at the top of your listing</span>
                            <div class="error-block text-danger">{{ form.company_logo.errors }}</div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group {% if form.company_url.errors %} has-error{% endif %}col-md-6">
                            <label>Company Website URL</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_url class+="form-control form-control-lg" %}
                            <span class="input-text">Example: https://mybusiness.com/</span>
                            <div class="error-block text-danger">{{ form.company_url.errors }}</div>
                        </div>
                        <div class="form-group {% if form.company_email.errors %} has-error{% endif %}col-md-6">
                            <label>Email</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_email class+="form-control form-control-lg" %}
                            <div class="error-block text-danger">{{ form.company_email.errors }}</div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group {% if form.company_description.errors %} has-error{% endif %}col-md-12">
                            <label>Company Description</label>
                            <p class="required-field"> ●</p>
                            {% render_field form.company_description class+="form-control form-control-lg" %}
                            <div class="error-block text-danger">{{ form.company_description.errors }}</div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-danger float-right">Submit</button>
                </form>
            </div>
        </section>
    </div>
</main>
{% endblock content %}

apps/jobs/templates/jobs/job_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% load widget_tweaks %}
<main role="main">
    <div class="container">
        <section class="job-nav row">
            <a href="{% url 'jobs:jobs-home' %}?job_category={{job_post.job_category}}">
                <p style="float: right;"> See more {{job_post.get_job_category_display}} jobs<span
                        id="arrow-right">→</span>
                </p>
            </a><a href="/">
                <p style="float: left;z-index: 999;"><span id="arrow-left">←</span> Back to all jobs </p>
            </a>
        </section>
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <div class="col-md-12">
                        <div class="job-post-header-container">
                            <h3> Posted {{job_post.created_on|date:"M d" }}
                            </h3>
                            <h1> {{job_post.title}} </h1>
                            <a href="{% url 'jobs:jobs-home' %}?job_type={{job_post.job_type}}">
                                <span class="post-tag">{{job_post.get_job_type_display}}</span>
                            </a>
                            <a href="{% url 'jobs:jobs-home' %}?job_category={{job_post.job_category}}">
                                <span class="post-tag">{{job_post.get_job_category_display}}</span>
                            </a>
                            <a
                                href="{% url 'jobs:jobs-home' %}?regional_restrictions={{job_post.regional_restrictions}}">
                                <span class="post-tag">{{job_post.get_regional_restrictions_display}}</span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="listing-container">
                            {{job_post.description|safe}}
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="listing-tools">
                            <a target="_blank" id="job-cta-alt-2" href="{{job_post.application_url}}"
                                class="btn btn-danger">
                                Apply for this position
                            </a>
                        </div>
                        <section class="jobs related-jobs">
                            <article>
                                <h2> Related Jobs <span style="float: right;"><a
                                            href="{% url 'jobs:jobs-home' %}?job_category={{job_post.job_category}}">
                                            See more
                                            {{job_post.get_job_category_display}} jobs<span
                                                id="arrow-right">→</span></a></span>
                                </h2>
                                {% include "jobs/job_posts.html" %}
                            </article>
                        </section>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="company-details">
                    <a href="{% url 'jobs:company-detail' pk=job_post.company.id %}">
                        <div class="company-logo" style="background-image: url({{job_post.company.logo.url}});"
                            loading="lazy">
                        </div>
                    </a>
                    <h2><a href="{% url 'jobs:company-detail' pk=job_post.company.id %}">{{job_post.company.name}}</a>
                    </h2>
                    <h3>
                        <i class="fas fa-map-marker-alt"></i> {{job_post.job_location}}
                    </h3>
                    <h3><a target="_blank" href="{{job_post.company.url}}">
                            <i class="fas fa-globe-americas"></i> View website
                        </a>
                    </h3>
                    <h4> Jobs posted: {{job_post.company.num_jobs_posted}} </h4>
                    <a target="_blank" id="job-cta-alt-2" href="{{job_post.application_url}}" class="btn btn-danger">
                        Apply for this position
                    </a>
                    <a href="/">
                        <h5> View all jobs<span id="arrow-right">→</span></h5>
                    </a>
                    <br>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

apps/jobs/templates/jobs/job_list.html
{% extends "base.html" %}

{% block content %}

{% include "banner.html" %}
<main role="main">
    <div class="container">
        {% for category, posts in job_posts.items %}
        <section class="jobs row">
            <div class="col">
                <article class="mx-auto">
                    <h2>
                        <a class="text-dark h4 category" href="?job_category={{category}}">{{category}}
                            Jobs</a>
                        <span class="font-weight-light h6 latest_post">
                            Latest post about {{posts.0.created_on|timesince}} ago
                        </span>
                    </h2>
                    {% include "jobs/job_posts.html" %}
                </article>
            </div>
        </section>
        {% endfor %}
    </div>
</main>
{% endblock content %}

apps/jobs/templates/jobs/job_posts.html
<ul>
    {% for post in posts %}
    <li class="feature">
        <div class="highlight-bar"></div>
        <div class="company-logo">
            <a href="{% url 'jobs:company-detail' pk=post.company.id %}">
                {% if post.company.logo %}
                <div class="flag-logo" style="background-image: url({{post.company.logo.url}})" loading="lazy">
                </div>
                {% endif %}
            </a>
        </div>
        <a href="{% url 'jobs:job-detail' pk=post.id %}">
            <span class="company">{{post.company.name}}</span>
            <br>
            <span class="title">{{post.title}}</span>
            <span class="date_posted">{{post.created_on|date:"M d"}}</span>
            <br>
            <span class="company">{{post.get_job_type_display}}</span>
            <span>/</span>
            <span class="region company">{{post.job_location}}</span>
        </a>
    </li>
    {% endfor %}
</ul>