apps/jobs/urls.py
from django.urls import path

from . import views

app_name = "jobs"

urlpatterns = [
    path("", views.JobListView.as_view(), name="jobs-home"),
    path("jobs/new/", views.JobCreateView.as_view(), name="job-create"),
    path("jobs/<int:pk>/", views.JobDetailView.as_view(), name="job-detail"),
    path(
        "companies/<int:pk>/", views.CompanyDetailView.as_view(), name="company-detail"
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "",
        include("jobs.urls", namespace="jobs"),
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/banner.html
<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="text-center header-logo">
            {% if header_name %}
            Remote {{header_name}} jobs
            {% else %}
            We Work From Home
            {% endif %}
        </h1>
        <section class="intro">
            {% if header_name %}
            <p class="text-center">
                Find all <strong>{{header_name}}</strong> remote jobs below
            </p>
            {% else %}
            <p class="text-center">We Work From Home is a simple Python/Django clone of <strong>
                    weworkremotely.com</strong></p>
            {% endif %}
        </section>
        <p class="text-center">
            <a href="{% url 'jobs:job-create' %}" class='btn btn-danger btn-lg'>Post a job</a>
        </p>
    </div>
</div>

templates/base.html
{% load static %}
{% load compress %}
<!DOCTYPE html>
<html>

<head>
  {% block head %}
  {% block meta %}
  {{ form.media }}
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% endblock meta %}
  <title> WWFH | WWR Clone {% block title %}{% endblock %}</title>
  {% block base_stylesheets %}
  <!-- Jquery-->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>


  <!-- Bootstrap 4 Js -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
    crossorigin="anonymous"></script>

  <!-- Custom Bootstrap 4 Css -->
  {% compress css %}
  <link rel="stylesheet" type="text/x-scss" href="{% static 'css/base_styles.scss' %}" />
  {% endcompress %}

  <!-- Fontawesome -->
  <script src="https://kit.fontawesome.com/50492a28bc.js" crossorigin="anonymous"></script>

  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/github-fork-ribbon-css/0.2.3/gh-fork-ribbon.min.css" />

  {% endblock base_stylesheets %}
  {% endblock head %}
</head>

<body>
  {% block body %}
  <nav class="navbar fixed-top navbar-expand-lg px-md-10 navbar-light bg-light">
    <a class="navbar-brand" href="/">
      WWFH
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#togglerControls"
      aria-controls="togglerControls" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="togglerControls">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            {% for category in categories %}
            {% if category.slug in 'full_time,contract' %}
            <a class="dropdown-item" href="{% url 'jobs:jobs-home' %}?job_type={{category.slug}}">{{category.name}}</a>
            {% else %}
            <a class="dropdown-item"
              href="{% url 'jobs:jobs-home' %}?job_category={{category.slug}}">{{category.name}}</a>
            {% endif %}
            {% endfor %}
          </div>
        </li>
        {% if not request.path == '/jobs/new/' %}
        <li class="nav-item post-job">
          <form class="form-inline navbar-nav">
            <a href="{% url 'jobs:job-create' %}" class='btn btn-danger'>Post a job</a>
          </form>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% block content %}
  {% endblock content %}

  <footer>
    <a class="github-fork-ribbon right-bottom fixed" href="https://github.com/iamjackwachira/wwfh"
      data-ribbon="Fork me on GitHub" title="Fork me on GitHub">Fork me on GitHub</a>
  </footer>
  {% endblock body %}
</body>

</html>